# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=50)),
                ('dp', models.CharField(max_length=5)),
                ('provincia', models.CharField(default='Asturias', max_length=25)),
                ('fecha_alta', models.DateField(default=datetime.datetime(2018, 9, 23, 16, 25, 1, 569101, tzinfo=utc))),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('n_ir', models.CharField(max_length=50)),
                ('expediente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_alta', models.DateField(default=datetime.datetime(2018, 9, 23, 16, 25, 1, 569963, tzinfo=utc))),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('categoriair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega.CategoriaIR')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega.Centro')),
            ],
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=50)),
                ('dp', models.CharField(max_length=5)),
                ('provincia', models.CharField(default='Asturias', max_length=25)),
                ('siglas', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega.Titular'),
        ),
    ]
