# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('IR', 'Servicio')
    ]
