# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0003_auto_20180924_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='titular',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
