# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0004_auto_20180927_2302'),
        ('mega', '0004_auto_20180928_1259'),
    ]

    operations = [
    ]
