# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0006_centro_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=50)),
                ('estudios', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('n_serie', models.CharField(blank=True, max_length=25, null=True)),
                ('n_sistema', models.CharField(blank=True, max_length=25, null=True)),
                ('referencia', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega.Modalidad'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega.Servicio'),
        ),
    ]
