# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0008_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('titulacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('nid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('titulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mega.Titulacion')),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='titular',
            field=models.ForeignKey(db_column='titular_nid', default='0', on_delete=django.db.models.deletion.CASCADE, to='mega.Trabajador'),
        ),
    ]
