# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0009_auto_20190206_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licencia',
            name='fecha_concesion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
