# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0010_auto_20190206_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='titular',
        ),
        migrations.AddField(
            model_name='licencia',
            name='trabajador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mega.Trabajador'),
            preserve_default=False,
        ),
    ]
