# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0011_auto_20190209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licencia',
            name='trabajador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mega.Trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nid',
            field=models.CharField(max_length=20),
        ),
    ]
